# Colors (Nevergrove $VARIANT)

[colors.primary]
background = "$BG1"
foreground = "$FG"
dim_foreground = "$FGDIM"

[colors.cursor]
text = "$BG0"
cursor = "$GRAY2"

[colors.selection]
text = "$WHITE"
background = "$VIS"

[colors.normal]
black   = "$BG0"
red     = "$RED"
green   = "$GREEN"
yellow  = "$YELLOW"
blue    = "$BLUE"
magenta = "$PURPLE"
cyan    = "$TEAL"
white   = "$FG"

[colors.bright]
black   = "$BG0"
red     = "$RED"
green   = "$GREEN"
yellow  = "$YELLOW"
blue    = "$BLUE"
magenta = "$PURPLE"
cyan    = "$TEAL"
white   = "$FG"

[colors.dim]
black   = "$BLACK"
red     = "$BGRED"
green   = "$BGGREEN"
yellow  = "$BGYELLOW"
blue    = "$BGBLUE"
magenta = "$BGPURPLE"
cyan    = "$BGTEAL"
white   = "$FGDIM"