# Colors (Nevergrove maple)

[colors.primary]
background = "#312725"
foreground = "#e6d9bc"
dim_foreground = "#877b6f"

[colors.cursor]
text = "#251d1d"
cursor = "#a69a9a"

[colors.selection]
text = "#e6e6e5"
background = "#364d48"

[colors.normal]
black   = "#251d1d"
red     = "#e96a69"
green   = "#9bc577"
yellow  = "#dfb767"
blue    = "#70acc2"
magenta = "#cb81cb"
cyan    = "#74be94"
white   = "#e6d9bc"

[colors.bright]
black   = "#4f4140"
red     = "#e99696"
green   = "#bedaa5"
yellow  = "#e6ca93"
blue    = "#9bc5d4"
magenta = "#daa9da"
cyan    = "#a5d5ba"
white   = "#efe9dc"

[colors.dim]
black   = "#1d1c1d"
red     = "#552e2d"
green   = "#454931"
yellow  = "#54422e"
blue    = "#3b4247"
magenta = "#523149"
cyan    = "#3c473b"
white   = "#877b6f"