# Colors (Nevergrove maple)

[colors.primary]
background = "#312526"
foreground = "#e6d9bc"
dim_foreground = "#877a70"

[colors.cursor]
text = "#251d1f"
cursor = "#a49898"

[colors.selection]
text = "#e6e6e5"
background = "#364d48"

[colors.normal]
black   = "#251d1f"
red     = "#e96a69"
green   = "#9bc577"
yellow  = "#dfb767"
blue    = "#70acc2"
magenta = "#cb81cb"
cyan    = "#74be94"
white   = "#e6d9bc"

[colors.bright]
black   = "#4f4041"
red     = "#e99696"
green   = "#bedaa5"
yellow  = "#e6ca93"
blue    = "#9bc5d4"
magenta = "#e0aee0"
cyan    = "#a5d5ba"
white   = "#efe9dc"

[colors.dim]
black   = "#1d1c1d"
red     = "#552d2d"
green   = "#454831"
yellow  = "#54412e"
blue    = "#3b4147"
magenta = "#523049"
cyan    = "#3c463b"
white   = "#877a70"