# Colors (Nevergrove maple light)

[colors.primary]
background = "#f9f1f2"
foreground = "#474238"
dim_foreground = "#9c938f"

[colors.cursor]
text = "#f9f1f2"
cursor = "#716565"

[colors.selection]
text = "#242324"
background = "#b9e1d2"

[colors.normal]
black   = "#f9f1f2"
red     = "#d02525"
green   = "#7faa0e"
yellow  = "#e09600"
blue    = "#3a94c5"
magenta = "#c742c7"
cyan    = "#279b65"
white   = "#474238"

[colors.bright]
black   = "#dececf"
red     = "#8c3131"
green   = "#5f6f34"
yellow  = "#8b630e"
blue    = "#1a4b66"
magenta = "#7b3d7b"
cyan    = "#1a6042"
white   = "#32302a"

[colors.dim]
black   = "#242324"
red     = "#eebebf"
green   = "#dbdfc4"
yellow  = "#edd7c1"
blue    = "#cfd7df"
magenta = "#ebc2e2"
cyan    = "#d0ddd1"
white   = "#9c938f"