# Colors (Nevergrove jacaranda light)

[colors.primary]
background = "#f1f2f9"
foreground = "#474238"
dim_foreground = "#969394"

[colors.cursor]
text = "#f1f2f9"
cursor = "#6b6670"

[colors.selection]
text = "#242324"
background = "#e7d2b3"

[colors.normal]
black   = "#f1f2f9"
red     = "#d02525"
green   = "#7faa0e"
yellow  = "#e09600"
blue    = "#3a94c5"
magenta = "#c742c7"
cyan    = "#279b65"
white   = "#474238"

[colors.bright]
black   = "#cecede"
red     = "#8c3131"
green   = "#5f6f34"
yellow  = "#8b630e"
blue    = "#1a4b66"
magenta = "#7b3d7b"
cyan    = "#1a6042"
white   = "#32302a"

[colors.dim]
black   = "#242324"
red     = "#e4bec8"
green   = "#d1dfcd"
yellow  = "#e3d7ca"
blue    = "#c5d7e8"
magenta = "#e1c2eb"
cyan    = "#c6ddda"
white   = "#969394"