# Colors (Nevergrove jacaranda )

[colors.primary]
background = "#262631"
foreground = "#e6d9bc"
dim_foreground = "#827b75"

[colors.cursor]
text = "#1d1e25"
cursor = "#9e99a3"

[colors.selection]
text = "#ebebea"
background = "#564d37"

[colors.normal]
black   = "#1d1e25"
red     = "#ea6c6b"
green   = "#9bc775"
yellow  = "#e2b864"
blue    = "#6cadc6"
magenta = "#cf7dcf"
cyan    = "#72c094"
white   = "#e6d9bc"

[colors.bright]
black   = "#414150"
red     = "#e49b9b"
green   = "#bed4ab"
yellow  = "#e4cb9a"
blue    = "#a5c8d4"
magenta = "#d9abd9"
cyan    = "#a8d2ba"
white   = "#efe9dc"

[colors.dim]
black   = "#1a191a"
red     = "#4b2e37"
green   = "#3c483a"
yellow  = "#4b4137"
blue    = "#324150"
magenta = "#493052"
cyan    = "#334644"
white   = "#827b75"